### ISSUE TITLE
OpenFoam: can't access CFT

### ISSUE THREAD

**Issue by ubik76** [aws-samples/awsome-hpc#96]
when I try to deploy Cloud9 from the CFT I get this error msg: "Cannot open this file because of an error.: https://awsome-hpc.s3.amazonaws.com/cf_hpc_solutions_cloud9.yaml must reference a valid S3 object to which you have access."

**Comment by mhuguesaws** [comment]
The Cloudformation template access has been restored. Thanks for reporting.
